// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcekUthfbFnDzukT94j_Mk7tzrwhOWTzw',
    appId: '1:665077614024:web:751b5200317f851d166cfd',
    messagingSenderId: '665077614024',
    projectId: 'repalogicmessanger',
    authDomain: 'repalogicmessanger.firebaseapp.com',
    storageBucket: 'repalogicmessanger.firebasestorage.app',
    measurementId: 'G-TE6CPFZ79J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaBELwMahoykq0RYlXeRAilrYvnWioVeE',
    appId: '1:665077614024:android:5c5a946eebe90dc6166cfd',
    messagingSenderId: '665077614024',
    projectId: 'repalogicmessanger',
    storageBucket: 'repalogicmessanger.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN5YU_Le_-20rLGuwZeh9SeDsA6hJdcvc',
    appId: '1:665077614024:ios:036f7ab03d9e5318166cfd',
    messagingSenderId: '665077614024',
    projectId: 'repalogicmessanger',
    storageBucket: 'repalogicmessanger.firebasestorage.app',
    iosBundleId: 'com.example.repalogicAuthenticator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN5YU_Le_-20rLGuwZeh9SeDsA6hJdcvc',
    appId: '1:665077614024:ios:036f7ab03d9e5318166cfd',
    messagingSenderId: '665077614024',
    projectId: 'repalogicmessanger',
    storageBucket: 'repalogicmessanger.firebasestorage.app',
    iosBundleId: 'com.example.repalogicAuthenticator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcekUthfbFnDzukT94j_Mk7tzrwhOWTzw',
    appId: '1:665077614024:web:9b477712b7d22cdb166cfd',
    messagingSenderId: '665077614024',
    projectId: 'repalogicmessanger',
    authDomain: 'repalogicmessanger.firebaseapp.com',
    storageBucket: 'repalogicmessanger.firebasestorage.app',
    measurementId: 'G-WH5G2LN1RT',
  );
}
